# coding: utf-8

LOCAL_INFLUX_URL_ENV_VAR_NAME: str = 'MONIT_SYNC_LOCAL_URL'
DEFAULT_LOCAL_INFLUX_URL: str = 'http://ai-sprint-monit-influxdb:8086/'
LOCAL_INFLUX_TOKEN_ENV_VAR_NAME: str = 'MONIT_SYNC_LOCAL_TOKEN'
LOCAL_INFLUX_ORG_ENV_VAR_NAME: str = 'MONIT_SYNC_LOCAL_ORG'
DEFAULT_INFLUX_ORG: str = 'ai-sprint'
LOCAL_INFLUX_BUCKET_ENV_VAR_NAME: str = 'MONIT_SYNC_LOCAL_BUCKET'
REMOTE_INFLUX_URL_ENV_VAR_NAME: str = 'MONIT_SYNC_REMOTE_URL'
REMOTE_INFLUX_TOKEN_ENV_VAR_NAME: str = 'MONIT_SYNC_REMOTE_TOKEN'
REMOTE_INFLUX_ORG_ENV_VAR_NAME: str = 'MONIT_SYNC_REMOTE_ORG'
REMOTE_INFLUX_BUCKET_ENV_VAR_NAME: str = 'MONIT_SYNC_REMOTE_BUCKET'
ADDITIONAL_TAGS_ENV_VAR_NAME: str = 'MONIT_SYNC_ADDITIONAL_TAGS'
